tailwind.config = {
      darkMode: "class",
      theme: {
        extend: {
          "colors": {
            "on-secondary-fixed": "#0f0069",
            "secondary-fixed-dim": "#c3c0ff",
            "tertiary-fixed": "#ffddb8",
            "on-surface-variant": "#9badb5",
            "background": "#071727",
            "on-tertiary-fixed": "#2a1700",
            "surface-container-highest": "#1c3245",
            "secondary-fixed": "#e2dfff",
            "surface-bright": "#0d2a3c",
            "primary": "#86e0cb",
            "surface-container-high": "#143044",
            "surface": "#071727",
            "primary-fixed-dim": "#4edea3",
            "error": "#ff6c77",
            "on-secondary": "#ffffff",
            "inverse-primary": "#4edea3",
            "on-background": "#f0f7f9",
            "tertiary-fixed-dim": "#ffb95f",
            "tertiary-container": "#e29100",
            "on-primary": "#031c17",
            "inverse-surface": "#f0f7f9",
            "on-secondary-fixed-variant": "#3323cc",
            "surface-container": "#0b2034",
            "on-tertiary": "#ffffff",
            "surface-container-lowest": "#03080e",
            "surface-dim": "#071727",
            "on-tertiary-container": "#523200",
            "outline": "#233e50",
            "secondary": "#4b41e1",
            "secondary-container": "#645efb",
            "on-tertiary-fixed-variant": "#653e00",
            "on-error-container": "#ff6c77",
            "surface-container-low": "#091c2d",
            "error-container": "#4a0b12",
            "on-primary-fixed-variant": "#005236",
            "tertiary": "#f4c873",
            "on-error": "#ffffff",
            "on-secondary-container": "#fffbff",
            "inverse-on-surface": "#071727",
            "primary-fixed": "#6ffbbe",
            "on-primary-fixed": "#002113",
            "surface-tint": "#006c49",
            "surface-variant": "#dfe2f1",
            "on-surface": "#f0f7f9",
            "primary-container": "#0c453b",
            "on-primary-container": "#86e0cb",
            "outline-variant": "#1c3245"
          },
          "borderRadius": {
            "DEFAULT": "0.25rem",
            "lg": "0.5rem",
            "xl": "0.75rem",
            "2xl": "1rem",
            "3xl": "1.5rem",
            "full": "9999px"
          },
          "fontFamily": {
            "headline-lg": ["DM Sans"],
            "body-sm": ["DM Sans"],
            "body-lg": ["DM Sans"],
            "display-hero": ["DM Sans"],
            "headline-md": ["DM Sans"],
            "body-md": ["DM Sans"],
            "label-mono": ["JetBrains Mono"],
            "headline-sm": ["DM Sans"]
          }
        }
      }
    };
